# Funding sources for BlazeKV
# Add your real URLs before publishing
github: manishkumarbarla06-bot
patreon: https://www.patreon.com/yourname
paypal: https://www.paypal.me/yourname
other: 
  - name: Ko-fi
    url: https://ko-fi.com/yourname
